### ISSUE TITLE
Download links no longer work.

### ISSUE THREAD

**Issue by milolethbridge** [msfreaks/Sidder#2]
Sorry, a bit of a bad issue submit as it's not necessarily an issue with the code.

The OneDrive links on the blog no longer are active. For the people that would just like the .exe, would it be possible to add the latest to the releases section here?

**Comment by StyleTec** [comment]
@milolethbridge As I will keep the development running, binaries will be provided at the release section, once I have the upcoming version 2.7 finished

**Comment by StyleTec** [comment]
Published first release on GitHub.

[https://github.com/msfreaks/Sidder/releases](https://github.com/msfreaks/Sidder/releases)
