### ISSUE TITLE
Contributor request

### ISSUE THREAD

**Issue by StyleTec** [msfreaks/Sidder#3]
Hey Arjan,

I've generally got some really cool Ideas for this project and would like to keep the development of it up and running.
Are you interested in contributors and if so, would you mind adding me as one on the repo, so that I can directly push code into it, without the need of pull requests for each change?
Also I would like to be able to configure an action for publishing releases inside the repo, as already requested by #2 

Thanks,
Bastian

**Comment by msfreaks** [comment]
Hi Bastian, contributor invite is sent.

**Comment by StyleTec** [comment]
Thank you, Arjan :)
