### ISSUE TITLE
Add SHA256 Hash information for Sidder.exe

### ISSUE THREAD

**Issue by kezcik** [msfreaks/Sidder#4]
Since this Application is distributed as an exe file that is run as an administrator on RDS Servers I believe there should be the sha256 hash advertised with the download like Microsoft Powertoys does.
![image](https://github.com/msfreaks/Sidder/assets/63767776/130e1de7-c157-44aa-9dac-3a1581e28fc3)

**Comment by StyleTec** [comment]
@kezcik added file hash for release 2.7.1 and will publish them for future releases.

Short note:
You need to trust my compilation and Microsoft (which owns GitHub). If you use hashes as a security feature, you should consider compiling your own binary from source in addition to review the source code.
